<?php

include_once('hot_core.features.inc');

/**
 * Implementation of hook_init()
 */
function hot_core_init() {

  // Set the current page title in the breadcrumb
  if (variable_get('hot_core_breadcrumb_title', TRUE)) {
    $breadcrumb = drupal_get_breadcrumb();
    if (count($breadcrumb) && drupal_get_title()) {
      $breadcrumb[] = drupal_get_title();

      // If it is the homepage, remove the breadcrumb
      if (drupal_is_front_page()) {
        $breadcrumb = array();
      }
      drupal_set_breadcrumb($breadcrumb);
    }
  }
}

/**
 * Implements hook_apps_app_info()
 */
function hot_core_apps_app_info() {
  return array(
    'configure form' => 'hot_core_configure_form',
  );
}

/**
 * Implemenets hook_page_build().
 */
function hot_core_page_build(&$page) {
  // This fixes a bug that causes @font-face declarations to break in IE6-8.
  // @see http://www.smashingmagazine.com/2012/07/11/avoiding-faux-weights-styles-...
  $path = drupal_get_path('module', 'hot_core');
  drupal_add_css($path . '/css/hotsauce-fonts-ie-open-sans.css', array('group' => CSS_THEME, 'every_page' => TRUE, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
  drupal_add_css($path . '/css/hotsauce-fonts-ie-open-sans-bold.css', array('group' => CSS_THEME, 'every_page' => TRUE, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
  drupal_add_css($path . '/css/hotsauce-fonts-ie-open-sans-italic.css', array('group' => CSS_THEME, 'every_page' => TRUE, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
  drupal_add_css($path . '/css/hotsauce-fonts-ie-open-sans-bold-italic.css', array('group' => CSS_THEME, 'every_page' => TRUE, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
}

/**
 * Configuration Form for HotCore!
 */
function hot_core_configure_form($form, &$form_state) {
  $form = array();

  $form['hot_core_breadcrumb_title'] = array(
    '#title' => t('Append Page Title to Site Breadcrumb'),
    '#type' => 'select',
    '#required' => TRUE,
    '#options' => array(
      '1' => 'Enabled',
      '0' => 'Disabled',
    ),
    '#default_value' => variable_get('hot_core_breadcrumb_title', 1),
    '#description' => t('Do you want hotsauce to append the page title to the site breadcrumb?'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_preprocess_html()
 *
 * We are telling the site that everything is a region-content. This is important since
 * when we disable the block module it loses this classes which some things assume for generalized
 * CSS considerations (i.e. Bartik's spacing of ul/ol).
 */
function hot_core_preprocess_html(&$variables) {
  $variables['classes_array'][] = 'region-content';
}

/**
 * Implements hook_apps_servers_info()
 */
function hot_core_apps_servers_info() {
  return array(
    'hotapps' => array(
      'title' => 'HotApps!',
      'description' => 'First generation HotApps! for the people.',
      'manifest' => 'http://apps.kalamuna.com/hotapps1',
    ),
  );
}

/**
 * Implements hook_module_implements_alter().
 */
function hot_core_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'css_alter' || $hook == 'modules_enabled') {
    $group = $implementations['hot_core'];
    unset($implementations['hot_core']);
    $implementations['hot_core'] = $group;
  }
}

/**
 * Implementation hook_element_info_alter().
 */
function hot_core_element_info_alter(&$type) {
  // Rather than implementing hook_css_alter(), we'll add a custom pre render
  // function for the styles elemement. This is to allow us to override
  // seven_css_alter(), which always runs after any module's implementation.
  if (isset($type['styles']['#pre_render'])) {
    array_unshift($type['styles']['#pre_render'], 'hot_core_pre_render_styles');
  }
}

/**
 * Implements hook_modules_enabled().
 *
 * This hook is implemented to assign some default permissions for panelizer's handling
 * of taxonomy terms. This has to be done in this hook to run after both features
 * and defaultconfig which power the functionality. Hopefully a more general solution
 * can be found. More information - http://drupal.org/node/1837312.
 */
function hot_core_modules_enabled($modules) {

  // Only run this logic if we are executing as part of an install profile
  // and only for this particular module.
  if (drupal_installation_attempted() && in_array('hot_core', $modules)) {

    // Rebuild some caches so this all works right
    taxonomy_features_rebuild('hot_core');
    drupal_static_reset('panelizer_entity_plugin_get_handler');

    // Define some permissions for the editor role
    if ($editor = user_role_load_by_name('editor')) {
      user_role_grant_permissions($editor->rid, array('administer panelizer taxonomy_term hotsauce_categories breadcrumbs'));
      user_role_grant_permissions($editor->rid, array('administer panelizer taxonomy_term hotsauce_categories content'));
      user_role_grant_permissions($editor->rid, array('administer panelizer taxonomy_term hotsauce_categories context'));
      user_role_grant_permissions($editor->rid, array('administer panelizer taxonomy_term hotsauce_categories defaults'));
      user_role_grant_permissions($editor->rid, array('administer panelizer taxonomy_term hotsauce_categories layout'));
      user_role_grant_permissions($editor->rid, array('administer panelizer taxonomy_term hotsauce_categories overview'));
      user_role_grant_permissions($editor->rid, array('administer panelizer taxonomy_term hotsauce_categories settings'));
    }

    // Define some permissions for the admin role
    if ($administrator = user_role_load_by_name('administrator')) {
      user_role_grant_permissions($administrator->rid, array('administer panelizer taxonomy_term hotsauce_categories breadcrumbs'));
      user_role_grant_permissions($administrator->rid, array('administer panelizer taxonomy_term hotsauce_categories content'));
      user_role_grant_permissions($administrator->rid, array('administer panelizer taxonomy_term hotsauce_categories context'));
      user_role_grant_permissions($administrator->rid, array('administer panelizer taxonomy_term hotsauce_categories defaults'));
      user_role_grant_permissions($administrator->rid, array('administer panelizer taxonomy_term hotsauce_categories layout'));
      user_role_grant_permissions($administrator->rid, array('administer panelizer taxonomy_term hotsauce_categories overview'));
      user_role_grant_permissions($administrator->rid, array('administer panelizer taxonomy_term hotsauce_categories settings'));
    }
  }
}

/**
 * Implementation of hook_css_alter()
 */
function hot_core_css_alter() {
  // Deprecated
}

/**
 * Pre render the styles element.
 */
function hot_core_pre_render_styles($elements) {
  $css = &$elements['#items'];

  // Installs the jQuery.UI themeroller theme to the theme.
  if (isset($css['misc/ui/jquery.ui.theme.css'])) {
    $css['misc/ui/jquery.ui.theme.css']['data'] = drupal_get_path('module', 'hot_core') . '/css/hotsauce-jquery-ui-theme.css';
  }

  if (isset($css['misc/ui/jquery.ui.dialog.css'])) {
    unset($css['misc/ui/jquery.ui.dialog.css']);
  }

  if (isset($css['misc/ui/jquery.ui.tabs.css'])) {
    unset($css['misc/ui/jquery.ui.tabs.css']);
  }

  return $elements;
}

/**
 * Implements hook_date_format_types()
 */
function hot_core_date_format_types() {
  return array(
    'hotsauce_time' => t('Time'),
    'hotsauce_day' => t('Day'),
  );
}

/**
 * Implements hook_date_formats().
 */
function hot_core_date_formats() {
  $formats = array();

  $formats[] = array(
    'type' => 'hotsauce_time',
    'format' => 'g:ia',
    'locales' => array(),
  );

  $formats[] = array(
    'type' => 'hotsauce_day',
    'format' => 'F j, Y',
    'locales' => array(),
  );

  return $formats;
}

/**
 * Helpfer function to get view modes
 */
function hot_core_view_mode_options() {
  $entity_info = entity_get_info('node');
  $options = array();
  if (!empty($entity_info['view modes'])) {
    foreach ($entity_info['view modes'] as $mode => $settings) {
      if (!in_array($mode, array('rss', 'search_index', 'search_result', 'token'))) {
        $options[$mode] = $settings['label'];
      }
    }
  }
  return $options;
}

/**
 * Helpfer function to import demo content for apps using Migrate.
 */
function _hot_core_import_demo_content($classes = array()) {
  // Ensure that migration classes are registered.
  migrate_get_module_apis(TRUE);

  // Process the migrations to import demo content.
  foreach ($classes as $class) {
    // Get a handle on our migration class.
    $migration = Migration::getInstance($class);

    // Disable message output from migrate ince this import is used within
    // the context of the Apps module where these messages make no sense.
    Migration::setDisplayFunction('_hot_core_null_message');

    // Process the migration.
    $migration->processImport();
  }
}

/**
 * Helpfer function to import demo content for apps using Migrate.
 */
function _hot_core_rollback_demo_content($classes = array()) {
  // Roll back the migrations to delete the demo content.
  foreach ($classes as $class) {
    // Get a handle on our migration class.
    $migration = Migration::getInstance($class);

    // Disable message output from migrate ince this import is used within
    // the context of the Apps module where these messages make no sense.
    Migration::setDisplayFunction('_hot_core_null_message');

    // Roll back the migration.
    $migration->processRollback();
  }

  // deregister the Migration classes since it will not exist after the
  // module is disabled.
  foreach ($classes as $class) {
    Migration::deregisterMigration($class);
  }
}

/**
 * Helpfer function to import demo content for apps using Migrate.
 */
function _hot_core_null_message($message, $level) {
  return;
}
